version: '2'

services:
        #    catalogue:
        #build:
        #    context: .
            #dockerfile: ./docker/catalogue/Dockerfile
            #    dockerfile: catalogue.Dockerfile
            #image: weaveworksdemos/catalogue
            #hostname: catalogue
            #restart: always
            #cap_drop:
            #- all
            #cap_add:
            #- NET_BIND_SERVICE
            #read_only: true
            #environment:
            #- reschedule=on-node-failure
            #ports:
                #- "8080:80"
                #- "80:80"
    catalogue-db:
        build:
            context: ./docker/catalogue-db/
        image: weaveworksdemos/catalogue-db
        hostname: catalogue-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            - reschedule=on-node-failure
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
